[supervisord]
nodaemon=true
logfile=/dev/null

[program:nginx]
command=nginx -g 'daemon off;'
autorestart=true

[program:php-fpm]
command=php-fpm -F
autorestart=true

[program:worker]
command=/bin/sh /app/worker.sh
autorestart=true
stderr_logfile=/dev/stdout
stdout_logfile=/dev/stdout